project_id = "mrbwhxaichbpvlqlgzrq"

[functions.homey-chat-completion]
verify_jwt = true

[functions.generate-recommendations]
verify_jwt = false

[functions.retell-webhook]
verify_jwt = false

[functions.create-retell-call]
verify_jwt = false
