// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrbwhxaichbpvlqlgzrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYndoeGFpY2hicHZscWxnenJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTA4MDQsImV4cCI6MjA2NTU2NjgwNH0.5zZ4Ti-CG3fvVYUH_ErPSzPXWoKRLtJ1VpFUu54bNcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);